only_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - block_based_kvo
  - capture_variable
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
  # - discouraged_object_literal
  - discouraged_optional_boolean
  # - discouraged_optional_collection
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  # - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  # - explicit_top_level_acl
  # - explicit_type_interface
  - extension_access_modifier
