only_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - block_based_kvo
  - capture_variable
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
  # - discouraged_object_literal
  - discouraged_optional_boolean
  # - discouraged_optional_collection
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  # - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  # - explicit_top_level_acl
  # - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  # - file_length
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - for_where
  # - force_cast
  - force_try
  # - force_unwrapping
  # - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - ibinspectable_in_extension
  - identical_operands
  # - identifier_name
  - implicit_getter
  - implicit_return
  # - implicitly_unwrapped_optional
  - inclusive_language
  # - indentation_width
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  # - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  # - missing_docs
  - modifier_order
  - multiline_arguments
  # - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  # - nesting
  - nimble_operator
  # - no_extension_access_modifier
  - no_fallthrough_only
  # - no_grouping_extension
  - no_space_in_method_call
  - notification_center_detachment
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  # - required_deinit
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - test_case_accessibility
  # - todo
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  # - trailing_whitespace
  # - type_body_length
  # - type_contents_order
  - type_name
  # - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  # - vertical_whitespace_between_cases
  # - vertical_whitespace_closing_braces
  # - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

# Severities

anyobject_protocol: error
array_init: error
attributes: error
balanced_xctest_lifecycle: error
block_based_kvo: error
capture_variable: error
class_delegate_protocol: error
closing_brace: error
closure_body_length: error
closure_end_indentation: error
closure_parameter_position: error
closure_spacing: error
collection_alignment: error
colon: error
comma: error
comment_spacing: error
compiler_protocol_init: error
computed_accessors_order: error
conditional_returns_on_newline: error
contains_over_filter_count: error
contains_over_filter_is_empty: error
contains_over_first_not_nil: error
contains_over_range_nil_comparison: error
control_statement: error
convenience_type: error
custom_rules: error
cyclomatic_complexity: error
deployment_target: error
discarded_notification_center_observer: error
discouraged_assert: error
discouraged_direct_init: error
# discouraged_object_literal: error
discouraged_optional_boolean: error
# discouraged_optional_collection: error
duplicate_enum_cases: error
duplicate_imports: error
dynamic_inline: error
empty_collection_literal: error
empty_count: error
empty_enum_arguments: error
empty_parameters: error
empty_parentheses_with_trailing_closure: error
empty_string: error
empty_xctest_method: error
enum_case_associated_values_count: error
expiring_todo: error
# explicit_acl: error
explicit_enum_raw_value: error
explicit_init: error
explicit_self: error
# explicit_top_level_acl: error
# explicit_type_interface: error
extension_access_modifier: error
fallthrough: error
fatal_error_message: error
file_header: error
# file_length: error
file_name: error
file_name_no_space: error
file_types_order: error
first_where: error
flatmap_over_map_reduce: error
for_where: error
# force_cast: error
force_try: error
# force_unwrapping: error
# function_body_length: error
function_default_parameter_at_end: error
function_parameter_count: error
generic_type_name: error
ibinspectable_in_extension: error
identical_operands: error
# identifier_name: error
implicit_getter: error
implicit_return: error
# implicitly_unwrapped_optional: error
inclusive_language: error
# indentation_width: error
inert_defer: error
is_disjoint: error
joined_default_parameter: error
large_tuple: error
last_where: error
leading_whitespace: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
legacy_hashing: error
legacy_multiple: error
legacy_nsgeometry_functions: error
legacy_objc_type: error
legacy_random: error
let_var_whitespace: error
# line_length: error
literal_expression_end_indentation: error
lower_acl_than_parent: error
mark: error
# missing_docs: error
modifier_order: error
multiline_arguments: error
# multiline_arguments_brackets: error
multiline_function_chains: error
multiline_literal_brackets: error
multiline_parameters: error
multiline_parameters_brackets: error
multiple_closures_with_trailing_closure: error
# nesting: error
nimble_operator: error
# no_extension_access_modifier: error
no_fallthrough_only: error
# no_grouping_extension: error
no_space_in_method_call: error
notification_center_detachment: error
nslocalizedstring_key: error
nslocalizedstring_require_bundle: error
nsobject_prefer_isequal: error
number_separator: error
object_literal: error
opening_brace: error
operator_usage_whitespace: error
operator_whitespace: error
optional_enum_case_matching: error
orphaned_doc_comment: error
overridden_super_call: error
override_in_extension: error
pattern_matching_keywords: error
prefer_nimble: error
prefer_self_type_over_type_of_self: error
prefer_zero_over_explicit_init: error
prefixed_toplevel_constant: error
private_action: error
private_outlet: error
private_over_fileprivate: error
private_subject: error
private_unit_test: error
prohibited_interface_builder: error
prohibited_super_call: error
protocol_property_accessors_order: error
quick_discouraged_call: error
quick_discouraged_focused_test: error
quick_discouraged_pending_test: error
raw_value_for_camel_cased_codable_enum: error
reduce_boolean: error
reduce_into: error
redundant_discardable_let: error
redundant_nil_coalescing: error
redundant_objc_attribute: error
redundant_optional_initialization: error
redundant_set_access_control: error
redundant_string_enum_value: error
redundant_type_annotation: error
redundant_void_return: error
# required_deinit: error
required_enum_case: error
return_arrow_whitespace: error
shorthand_operator: error
single_test_class: error
sorted_first_last: error
sorted_imports: error
statement_position: error
static_operator: error
strict_fileprivate: error
strong_iboutlet: error
superfluous_disable_command: error
switch_case_alignment: error
switch_case_on_newline: error
syntactic_sugar: error
test_case_accessibility: error
# todo: error
toggle_bool: error
trailing_closure: error
trailing_comma: error
trailing_newline: error
trailing_semicolon: error
# trailing_whitespace: error
# type_body_length: error
# type_contents_order: error
type_name: error
# unavailable_function: error
unneeded_break_in_switch: error
unneeded_parentheses_in_closure_argument: error
unowned_variable_capture: error
untyped_error_in_catch: error
unused_capture_list: error
unused_closure_parameter: error
unused_control_flow_label: error
unused_declaration: error
unused_enumerated: error
unused_import: error
unused_optional_binding: error
unused_setter_value: error
valid_ibinspectable: error
vertical_parameter_alignment: error
vertical_parameter_alignment_on_call: error
vertical_whitespace: error
# vertical_whitespace_between_cases: error
# vertical_whitespace_closing_braces: error
# vertical_whitespace_opening_braces: error
void_return: error
weak_delegate: error
xct_specific_matcher: error
xctfail_message: error
yoda_condition: error
